load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "io_helper",
    srcs = [
        "io_helper.cc",
    ],
    hdrs = [
        "io_helper.h",
    ],
    visibility = ["//tests/demuxer:__pkg__"],
)
