cc_library(
    name = "demuxer",
    srcs = [],
    hdrs = [
        "demuxer.h",
        "image_info.h"
    ],
    deps = ["@com_google_absl//absl/base"],
    copts = ["-std=c++17"],
    visibility = ["//libmphoto:__pkg__"]
)
